/**
 * Per-theme item display names: pure re-skin of the 20 pickups/weapons, no
 * gameplay change. The sky column is the canonical default and must stay in
 * sync with ITEM_META in config.ts (guarded by tests).
 */
import type { ItemType } from './types';
import { ITEM_META } from './config';

type ThemeNameTable = Record<ItemType, string>;

export const ITEM_NAMES: Record<string, ThemeNameTable> = {
  sky: {
    uzi: '冲锋枪',
    shotgun: '霰弹枪',
    laser: '激光炮',
    spread: '散射枪',
    bomb: '炸弹',
    bigbomb: '大炸弹',
    diagonalbomb: '斜炸弹',
    horizontalbomb: '横炸弹',
    linebomb: '线炸弹',
    shield: '护盾',
    boomerang: '回旋镖',
    doublebullets: '双子弹',
    speedboost: '加速',
    rapidfire: '连射',
    piercing: '穿透',
    magnet: '磁力',
    bigbullets: '大弹',
    shieldbooster: '护盾+',
    weaponduration: '持久',
    extralife: '生命',
  },
  space: {
    uzi: '脉冲机炮',
    shotgun: '星屑散射炮',
    laser: '光子射线',
    spread: '流星散射',
    bomb: '反物质炸弹',
    bigbomb: '超级反物质弹',
    diagonalbomb: '弧线飞弹',
    horizontalbomb: '横扫光束',
    linebomb: '轨道光束',
    shield: '力场护盾',
    boomerang: '轨道回旋刃',
    doublebullets: '双联装',
    speedboost: '引擎增压',
    rapidfire: '射速超载',
    piercing: '贯穿光束',
    magnet: '引力场',
    bigbullets: '重型弹头',
    shieldbooster: '强化力场',
    weaponduration: '能量持久',
    extralife: '备用能源',
  },
  forest: {
    uzi: '连珠弩',
    shotgun: '分裂箭',
    laser: '穿透神箭',
    spread: '扇叶飞刀',
    bomb: '荆棘炸弹',
    bigbomb: '巨型荆棘',
    diagonalbomb: '回旋斧',
    horizontalbomb: '横扫飞刀',
    linebomb: '穿林神箭',
    shield: '藤蔓护符',
    boomerang: '回旋飞叶',
    doublebullets: '双箭齐发',
    speedboost: '风行者',
    rapidfire: '疾风连射',
    piercing: '穿甲箭',
    magnet: '自然吸引',
    bigbullets: '巨型箭矢',
    shieldbooster: '古树庇护',
    weaponduration: '专注',
    extralife: '生命之叶',
  },
  sunset: {
    uzi: '双持左轮',
    shotgun: '霰弹猎枪',
    laser: '鹰眼狙击',
    spread: '扇形弹幕',
    bomb: '炸药桶',
    bigbomb: '大炸药桶',
    diagonalbomb: '甩炮',
    horizontalbomb: '横扫弹',
    linebomb: '直线穿甲弹',
    shield: '牛皮护符',
    boomerang: '牛仔套索',
    doublebullets: '双枪',
    speedboost: '快马靴',
    rapidfire: '快速拔枪',
    piercing: '穿甲弹',
    magnet: '淘金磁铁',
    bigbullets: '大号铅弹',
    shieldbooster: '坚韧牛皮',
    weaponduration: '耐力',
    extralife: '救命雪茄',
  },
  ocean: {
    uzi: '泡泡机关枪',
    shotgun: '贝壳霰弹炮',
    laser: '高压水炮',
    spread: '珊瑚散射',
    bomb: '深水炸弹',
    bigbomb: '巨型水雷',
    diagonalbomb: '弹射水雷',
    horizontalbomb: '潮汐横扫',
    linebomb: '高压水柱',
    shield: '气泡护盾',
    boomerang: '回旋贝壳',
    doublebullets: '双管水枪',
    speedboost: '洋流推进',
    rapidfire: '连珠水炮',
    piercing: '穿透水流',
    magnet: '漩涡吸附',
    bigbullets: '巨型水弹',
    shieldbooster: '深海气泡',
    weaponduration: '持久水压',
    extralife: '救生圈',
  },
  neon: {
    uzi: '离子冲锋枪',
    shotgun: '裂解炮',
    laser: '湮灭光束',
    spread: '量子散射',
    bomb: '聚变炸弹',
    bigbomb: '超级聚变弹',
    diagonalbomb: '相位飞弹',
    horizontalbomb: '横扫粒子',
    linebomb: '死光',
    shield: '能量屏障',
    boomerang: '回旋光刃',
    doublebullets: '双核弹头',
    speedboost: '超频',
    rapidfire: '火力全开',
    piercing: '相位穿透',
    magnet: '磁轨吸引',
    bigbullets: '重型离子',
    shieldbooster: '强化屏障',
    weaponduration: '持久核心',
    extralife: '备用电池',
  },
  snow: {
    uzi: '极地冲锋枪',
    shotgun: '雪崩炮',
    laser: '冰棱射线',
    spread: '冰晶散射',
    bomb: '冰雹炸弹',
    bigbomb: '巨型冰雹',
    diagonalbomb: '回旋冰镖',
    horizontalbomb: '雪崩横扫',
    linebomb: '冰柱贯穿',
    shield: '冰盾',
    boomerang: '回旋冰刃',
    doublebullets: '双发冰弹',
    speedboost: '雪地疾行',
    rapidfire: '急速射击',
    piercing: '冰锥穿透',
    magnet: '磁石',
    bigbullets: '巨型冰弹',
    shieldbooster: '极寒冰盾',
    weaponduration: '持久寒冰',
    extralife: '温暖篝火',
  },
  lava: {
    uzi: '熔岩机炮',
    shotgun: '岩浆喷发',
    laser: '熔核射线',
    spread: '火雨散射',
    bomb: '火山弹',
    bigbomb: '超级火山弹',
    diagonalbomb: '斜射岩浆',
    horizontalbomb: '烈焰横扫',
    linebomb: '熔岩柱',
    shield: '黑曜护盾',
    boomerang: '回旋火环',
    doublebullets: '双管岩浆',
    speedboost: '熔岩疾行',
    rapidfire: '爆燃连射',
    piercing: '熔岩穿透',
    magnet: '岩浆引力',
    bigbullets: '巨型熔岩弹',
    shieldbooster: '强化黑曜',
    weaponduration: '持久熔核',
    extralife: '生命熔核',
  },
};

/** Display name of an item under a theme; unknown themes fall back to sky. */
export function itemName(themeId: string, type: ItemType): string {
  return ITEM_NAMES[themeId]?.[type] ?? ITEM_NAMES.sky?.[type] ?? ITEM_META[type].name;
}
